### PR TITLE
Preserve interword spaces

### PR DESCRIPTION
**Pull request by Blu3train**
Changed "Ignore space characters difference" checkbox to "Preserve interword spaces".
Added preserve_interword_spaces configuration parameter to eliminate extra spaces for languages chi_sim, kor, jpn and tha at the OCR level.
I left the previous deletion code which could be used for the .gt.txt file.

### CODE REVIEW

**Comment by Blu3train** [comment]
I don't understand the reason for the conflict. I'm not very experienced with github

**Comment by buliasz** [comment]
> I don't understand the reason for the conflict. I'm not very experienced with github

It's just you've modified not the latest version. Please pull the current version first before you send modifications.

**Comment by buliasz** [comment]
I've updated it to include both in case someone needs space difference ignore also.

**Comment by Blu3train** [comment]
> It's just you've modified not the latest version. Please pull the current version first before you send modifications. I've resolved it for this one already.

How strange, I had done it

**Pull request closed without merging**
